/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'MyDepartmentAddressBook': RouteRecordInfo<'MyDepartmentAddressBook', '/basic/address-book', Record<never, never>, Record<never, never>>,
    'MyApproval': RouteRecordInfo<'MyApproval', '/basic/approval', Record<never, never>, Record<never, never>>,
    'MyBudgetReport': RouteRecordInfo<'MyBudgetReport', '/basic/budget-report', Record<never, never>, Record<never, never>>,
    'BudgetReportDetail': RouteRecordInfo<'BudgetReportDetail', '/basic/budget-report/detail', Record<never, never>, Record<never, never>>,
    'MyDepartmentColleague': RouteRecordInfo<'MyDepartmentColleague', '/basic/department-colleague', Record<never, never>, Record<never, never>>,
    'MyDocumentBorrow': RouteRecordInfo<'MyDocumentBorrow', '/basic/document-borrow', Record<never, never>, Record<never, never>>,
    'MyDocumentBorrowDetail': RouteRecordInfo<'MyDocumentBorrowDetail', '/basic/document-borrow/detail', Record<never, never>, Record<never, never>>,
    'MyDocumentBorrowForm': RouteRecordInfo<'MyDocumentBorrowForm', '/basic/document-borrow/form', Record<never, never>, Record<never, never>>,
    'MyReportFormReport': RouteRecordInfo<'MyReportFormReport', '/basic/report-form-report', Record<never, never>, Record<never, never>>,
    'ReportFormReportDetail': RouteRecordInfo<'ReportFormReportDetail', '/basic/report-form-report/detail', Record<never, never>, Record<never, never>>,
    'MyRequestForInstruction': RouteRecordInfo<'MyRequestForInstruction', '/basic/request-for-instruction', Record<never, never>, Record<never, never>>,
    'MyRequestForInstructionDetail': RouteRecordInfo<'MyRequestForInstructionDetail', '/basic/request-for-instruction/detail', Record<never, never>, Record<never, never>>,
    'MyRequestForInstructionForm': RouteRecordInfo<'MyRequestForInstructionForm', '/basic/request-for-instruction/form', Record<never, never>, Record<never, never>>,
    'MyTargetResponsibilityLetter': RouteRecordInfo<'MyTargetResponsibilityLetter', '/basic/target-responsibility-letter', Record<never, never>, Record<never, never>>,
    'MyTargetResponsibilityLetterDetail': RouteRecordInfo<'MyTargetResponsibilityLetterDetail', '/basic/target-responsibility-letter/detail', Record<never, never>, Record<never, never>>,
    'Charts': RouteRecordInfo<'Charts', '/charts', Record<never, never>, Record<never, never>>,
    'Counter': RouteRecordInfo<'Counter', '/counter', Record<never, never>, Record<never, never>>,
    'Home': RouteRecordInfo<'Home', '/home', Record<never, never>, Record<never, never>>,
    'AddressBook': RouteRecordInfo<'AddressBook', '/human-resource/address-book', Record<never, never>, Record<never, never>>,
    'AddressBookDetail': RouteRecordInfo<'AddressBookDetail', '/human-resource/address-book/detail', Record<never, never>, Record<never, never>>,
    'AddressBookForm': RouteRecordInfo<'AddressBookForm', '/human-resource/address-book/form', Record<never, never>, Record<never, never>>,
    'MyDepartmentAddressBook': RouteRecordInfo<'MyDepartmentAddressBook', '/human-resource/employee', Record<never, never>, Record<never, never>>,
    'EmployeeDetail': RouteRecordInfo<'EmployeeDetail', '/human-resource/employee/detail', Record<never, never>, Record<never, never>>,
    'EmployeeContract': RouteRecordInfo<'EmployeeContract', '/human-resource/employee-contract', Record<never, never>, Record<never, never>>,
    'EmployeeContractDetail': RouteRecordInfo<'EmployeeContractDetail', '/human-resource/employee-contract/detail', Record<never, never>, Record<never, never>>,
    'MyDocumentBorrow': RouteRecordInfo<'MyDocumentBorrow', '/human-resource/recruitment-intention', Record<never, never>, Record<never, never>>,
    'RecruitmentIntentionDetail': RouteRecordInfo<'RecruitmentIntentionDetail', '/human-resource/recruitment-intention/detail', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/login', Record<never, never>, Record<never, never>>,
    'Mock': RouteRecordInfo<'Mock', '/mock', Record<never, never>, Record<never, never>>,
    'Profile': RouteRecordInfo<'Profile', '/profile', Record<never, never>, Record<never, never>>,
    'ScrollCache': RouteRecordInfo<'ScrollCache', '/scroll-cache', Record<never, never>, Record<never, never>>,
    'Settings': RouteRecordInfo<'Settings', '/settings', Record<never, never>, Record<never, never>>,
    'UnoCSS': RouteRecordInfo<'UnoCSS', '/unocss', Record<never, never>, Record<never, never>>,
    'Workbench': RouteRecordInfo<'Workbench', '/workbench', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...all].vue': {
      routes: '404'
      views: never
    }
    'src/pages/basic/address-book/index.vue': {
      routes: 'MyDepartmentAddressBook'
      views: never
    }
    'src/pages/basic/approval/index.vue': {
      routes: 'MyApproval'
      views: never
    }
    'src/pages/basic/budget-report/index.vue': {
      routes: 'MyBudgetReport'
      views: never
    }
    'src/pages/basic/budget-report/detail.vue': {
      routes: 'BudgetReportDetail'
      views: never
    }
    'src/pages/basic/department-colleague/index.vue': {
      routes: 'MyDepartmentColleague'
      views: never
    }
    'src/pages/basic/document-borrow/index.vue': {
      routes: 'MyDocumentBorrow'
      views: never
    }
    'src/pages/basic/document-borrow/detail.vue': {
      routes: 'MyDocumentBorrowDetail'
      views: never
    }
    'src/pages/basic/document-borrow/form.vue': {
      routes: 'MyDocumentBorrowForm'
      views: never
    }
    'src/pages/basic/report-form-report/index.vue': {
      routes: 'MyReportFormReport'
      views: never
    }
    'src/pages/basic/report-form-report/detail.vue': {
      routes: 'ReportFormReportDetail'
      views: never
    }
    'src/pages/basic/request-for-instruction/index.vue': {
      routes: 'MyRequestForInstruction'
      views: never
    }
    'src/pages/basic/request-for-instruction/detail.vue': {
      routes: 'MyRequestForInstructionDetail'
      views: never
    }
    'src/pages/basic/request-for-instruction/form.vue': {
      routes: 'MyRequestForInstructionForm'
      views: never
    }
    'src/pages/basic/target-responsibility-letter/index.vue': {
      routes: 'MyTargetResponsibilityLetter'
      views: never
    }
    'src/pages/basic/target-responsibility-letter/detail.vue': {
      routes: 'MyTargetResponsibilityLetterDetail'
      views: never
    }
    'src/pages/charts/index.vue': {
      routes: 'Charts'
      views: never
    }
    'src/pages/counter/index.vue': {
      routes: 'Counter'
      views: never
    }
    'src/pages/home/index.vue': {
      routes: 'Home'
      views: never
    }
    'src/pages/human-resource/address-book/index.vue': {
      routes: 'AddressBook'
      views: never
    }
    'src/pages/human-resource/address-book/detail.vue': {
      routes: 'AddressBookDetail'
      views: never
    }
    'src/pages/human-resource/address-book/form.vue': {
      routes: 'AddressBookForm'
      views: never
    }
    'src/pages/human-resource/employee/index.vue': {
      routes: 'MyDepartmentAddressBook'
      views: never
    }
    'src/pages/human-resource/employee/detail.vue': {
      routes: 'EmployeeDetail'
      views: never
    }
    'src/pages/human-resource/employee-contract/index.vue': {
      routes: 'EmployeeContract'
      views: never
    }
    'src/pages/human-resource/employee-contract/detail.vue': {
      routes: 'EmployeeContractDetail'
      views: never
    }
    'src/pages/human-resource/recruitment-intention/index.vue': {
      routes: 'MyDocumentBorrow'
      views: never
    }
    'src/pages/human-resource/recruitment-intention/detail.vue': {
      routes: 'RecruitmentIntentionDetail'
      views: never
    }
    'src/pages/keepalive/index.vue': {
      routes: 'KeepAlive'
      views: never
    }
    'src/pages/login/index.vue': {
      routes: 'Login'
      views: never
    }
    'src/pages/mock/index.vue': {
      routes: 'Mock'
      views: never
    }
    'src/pages/profile/index.vue': {
      routes: 'Profile'
      views: never
    }
    'src/pages/scroll-cache/index.vue': {
      routes: 'ScrollCache'
      views: never
    }
    'src/pages/settings/index.vue': {
      routes: 'Settings'
      views: never
    }
    'src/pages/unocss/index.vue': {
      routes: 'UnoCSS'
      views: never
    }
    'src/pages/workbench/index.vue': {
      routes: 'Workbench'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
